// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var First = require("first/src/First.js");

describe("First", (function () {
        return Jest.test("hello!!!", (function () {
                      return Jest.Expect[/* toEqual */12]("Hello World!", Jest.Expect[/* expect */0](First.hello));
                    }));
      }));

/*  Not a pure module */
